const COUNTRIES = {
  Portugal: {
    Açores: [
      "Angra do Heroísmo",
      "Calheta",
      "Corvo",
      "Horta",
      "Lagoa",
      "Lajes das Flores",
      "Lajes do Pico",
      "Madalena",
      "Nordeste",
      "Ponta Delgada",
      "Povoacão",
      "Praia da Vitória",
      "Ribeira Grande",
      "Santa Cruz da Graciosa",
      "Santa Cruz das Flores",
      "São Roque do Pico",
      "Velas",
      "Vila Franca do Campo",
      "Vila do Porto",
    ],
    Aveiro: [
      "Albergaria-a-Velha",
      "Anadia",
      "Arouca",
      "Aveiro",
      "Águeda",
      "Castelo de Paiva",
      "Espinho",
      "Estarreja",
      "Feira",
      "Ílhavo",
      "Mealhada",
      "Murtosa",
      "Oliveira de Azeméis",
      "Oliveira do Bairro",
      "Ovar",
      "Sever do Vouga",
      "São João da Madeira",
      "Vagos",
      "Vale de Cambra",
    ],
    Beja: [
      "Aljustrel",
      "Almodovar",
      "Alvito",
      "Barrancos",
      "Beja",
      "Castro Verde",
      "Cuba",
      "Ferreira do Alentejo",
      "Moura",
      "Mértola",
      "Odemira",
      "Ourique",
      "Serpa",
      "Vidigueira",
    ],
    Braga: [
      "Amares",
      "Barcelos",
      "Braga",
      "Cabeceiras de Basto",
      "Celorico de Basto",
      "Esposende",
      "Fafe",
      "Guimarães",
      "Póvoa de Lanhoso",
      "Terras de Bouro",
      "Vieira do Minho",
      "Vila Nova de Famalicão",
      "Vila Verde",
      "Vizela",
    ],
    Bragança: [
      "Alfandêga da Fé",
      "Bragança",
      "Carrazeda de Ansiães",
      "Freixo de Espada à Cinta",
      "Macedo de Cavaleiros",
      "Miranda do Douro",
      "Mirandela",
      "Mogadouro",
      "Torre de Moncorvo",
      "Vila Flor",
      "Vimoso",
      "Vinhais",
    ],
    "Castelo Branco": [
      "Belmonte",
      "Castelo Branco",
      "Covilhã",
      "Fundão",
      "Idanha-a-Nova",
      "Oleiros",
      "Penamacor",
      "Proença-a-Nova",
      "Sertã",
      "Vila de Rei",
      "Vila Velha de Rodão",
    ],
    Coimbra: [
      "Arganil",
      "Cantanhede",
      "Coimbra",
      "Condeixa-a-Nova",
      "Figueira da Foz",
      "Góis",
      "Lousã",
      "Mira",
      "Miranda do Corvo",
      "Montemor-o-Velho",
      "Oliveira do Hospital",
      "Pampilhosa da Serra",
      "Penacova",
      "Penela",
      "Soure",
      "Tábua",
      "Vila Nova de Poiares",
    ],
    Évora: [
      "Alandroal",
      "Arraiolos",
      "Borba",
      "Évora",
      "Estremoz",
      "Montemor-o-Novo",
      "Moura",
      "Mourão",
      "Portel",
      "Redondo",
      "Reguengos de Monsaraz",
      "Vendas Novas",
      "Viana do Alentejo",
      "Vila Viçosa",
    ],
    Faro: [
      "Albufeira",
      "Alcoutim",
      "Aljezur",
      "Castro Marim",
      "Faro",
      "Lagoa",
      "Lagos",
      "Loulé",
      "Monchique",
      "Olhão",
      "Portimão",
      "Silves",
      "São Brás de Alportel",
      "Tavira",
      "Vila Rei de Santo António",
      "Vila do Bispo",
    ],
    Guarda: [
      "Aguiar da Beira",
      "Almeida",
      "Celorico de Basto",
      "Figueira de Castelo Rodrigo",
      "Fornos de Algodres",
      "Gouveia",
      "Guarda",
      "Manteigas",
      "Meda",
      "Pinhel",
      "Sabugal",
      "Seia",
      "Trancoso",
      "Vila Nova de Foz Côa",
    ],
    Leiria: [
      "Alcobaça",
      "Alvaiázere",
      "Ansião",
      "Batalha",
      "Bombarral",
      "Caldas da Rainha",
      "Castanheira de Pera",
      "Figueró dos Vinhos",
      "Leiria",
      "Marinha Grande",
      "Nazaré",
      "Pedrogão Grande",
      "Peniche",
      "Pombal",
      "Porto de Mós",
      "Óbidos",
    ],
    Lisboa: [
      "Alenquer",
      "Amadora",
      "Arruda dos Vinhos",
      "Azambuja",
      "Cadaval",
      "Cascais",
      "Lisboa",
      "Loures",
      "Lourinha",
      "Mafra",
      "Odivelas",
      "Oeiras",
      "Sintra",
      "Sobral de Monte Agraço",
      "Torres Vedras",
      "Vila Franca de Xira",
    ],
    Madeira: [
      "Calheta",
      "Câmara de Lobos",
      "Funchal",
      "Machico",
      "Ponta do Sol",
      "Porto Moniz",
      "Ribeira Brava",
      "Santa Cruz",
      "Santana",
      "São Vicente",
    ],
    Portalegre: [
      "Alter do Chão",
      "Arronches",
      "Avis",
      "Campo Maior",
      "Castelo de Vide",
      "Crato",
      "Elvas",
      "Fronteira",
      "Gavião",
      "Marvão",
      "Monforte",
      "Nisa",
      "Ponte de Sôr",
      "Portalegre",
      "Sousel",
    ],
    Porto: [
      "Amarante",
      "Baião",
      "Felgueiras",
      "Gondomar",
      "Lousada",
      "Maia",
      "Marco de Canaveses",
      "Matosinhos",
      "Paredes",
      "Paços de Ferreira",
      "Penafiel",
      "Porto",
      "Póvoa de Varzim",
      "Santo Tirso",
      "Trofa",
      "Valongo",
      "Vila do Conde",
      "Vila Nova de Gaia",
    ],
    Santarém: [
      "Abrantes",
      "Alcanena",
      "Almeirim",
      "Alpiarça",
      "Benavente",
      "Cartaxo",
      "Chamusca",
      "Constância",
      "Coruche",
      "Entroncamento",
      "Ferreira do Zêzere",
      "Golegã",
      "Mação",
      "Rio Maior",
      "Selvaterra de Magos",
      "Santarém",
      "Sardoal",
      "Tomar",
      "Torres Novas",
      "Vila Nova de Barquinha",
      "Vila Nova de Ourém",
    ],
    Setúbal: [
      "Alcochete",
      "Alcácer do Sal",
      "Almada",
      "Barreiro",
      "Grandola",
      "Moita",
      "Montijo",
      "Palmela",
      "Santiago do Cacém",
      "Seixal",
      "Sesimbra",
      "Setúbal",
      "Sines",
    ],
    "Viana do Castelo": [
      "Arcos de Valdevez",
      "Caminha",
      "Melgaço",
      "Monção",
      "Paredes de Coura",
      "Ponte da Barca",
      "Ponte de Lima",
      "Valença",
      "Viana do Castelo",
      "Vila Nova de Cerveira",
    ],
    Viseu: [
      "Armamar",
      "Carregal do Sal",
      "Castro Daire",
      "Cinfães",
      "Lamego",
      "Mangualde",
      "Moimenta da Beira",
      "Mortágua",
      "Nelas",
      "Oliveira de Frades",
      "Panalva do Castelo",
      "Penedono",
      "Resende",
      "Santa Comba Dão",
      "São João da Pesqueira",
      "Sernancelhe",
      "Sátão",
      "São Pedro do Sul",
      "Tabuaço",
      "Tarouca",
      "Tondela",
      "Vila Nova de Paiva",
      "Viseu",
      "Vouzela",
    ],
    "Vila Real": [
      "Alijó",
      "Boticas",
      "Chaves",
      "Mesão Frio",
      "Montalegre",
      "Murça",
      "Peso da Régua",
      "Ribeira de Pena",
      "Sabrosa",
      "Santa Marta de Penaguião",
      "Valpaços",
      "Vila Pouca de Aguiar",
      "Vila Real",
    ],
  },
};

export { COUNTRIES };
